name: Build after merge w/ docker
# Builds and runs tests after a PR is merged to main.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - name: Build
        run: go build -v ./...

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run:  docker build -t obscuro_enclave -f dockerfiles/enclave_local_build.Dockerfile .

      - name: Test
        run: go test -v -run TestDocker ./...
        env:
          DOCKER_TEST_ENABLED: true
