name: Build after merge w/ docker
# Builds and runs tests after a PR is merged to main.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - name: Build
        run: go build -v ./...

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run:  docker build -t obscuro_enclave -f dockerfiles/enclave_local_build.Dockerfile .

      - name: Test Docker
        run: go test -v -run TestDocker ./...
        env:
          DOCKER_TEST_ENABLED: true

      - name: Build geth qgv1.10.17
        run: bash ./integration/gethnetwork/build_geth_binary.sh --version=v1.10.17

      - name: Test Geth binary
        run: go test -v -run TestGeth ./...

      - name: Store simulation logs
        uses: actions/upload-artifact@v3
        with:
          name: sim-logs
          path: integration/.build/simulations/sim-log-*.txt
        if: always() # Ensures the artifacts are created even if the tests fail.
