name: Build PR
# Builds and runs tests on each push to a branch PR'ed against main.

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - name: Build
        run: go build -v ./...

      - name: Build geth qgv1.10.17
        run: bash ./integration/gethnetwork/build_geth_binary.sh --version=v1.10.17

      - name: Test
        run: go test -v ./...

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sim-logs
          path: integration/.build/simulations/simulation-result-*.txt
