name: Build PR
# Builds and runs tests on each push to a branch PR'ed against main.

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          USE_GETH_BINARY: true

      - name: Store simulation logs
        uses: actions/upload-artifact@v3
        with:
          name: sim-logs
          path: |
            integration/.build/simulations/sim-log-*.txt
            integration/.build/noderunner/noderunner-*.txt
        if: always() # Ensures the artifacts are created even if the tests fail.
