name: Manual Test
# Builds and runs docker tests on-demand.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - name: Build
        run: go build -v ./...

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run:  docker build -t obscuro_enclave -f dockerfiles/enclave_local_build.Dockerfile .

      - name: Test
        run: go test -v -tags docker ./...

      - name: Store simulation logs
        uses: actions/upload-artifact@v3
        with:
          name: sim-logs
          path: integration/.build/simulations/sim-log-*.txt
        if: always() # Ensures the artifacts are created even if the tests fail.
